services:
  - type: web
    name: code-debugger
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile

    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: "llama-3.3-70b-versatile"
